name: BI
channels:
  - conda-forge
  - bioconda
  - salilab
  - defaults
dependencies:
  - jupyter
  - pylint
  - pydocstyle
  - pycodestyle
  - pandas
  - matplotlib
  - jupyterlab
  - biopython
  - joblib
